---
- name: Installation Python et outils Data Science
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - jupyter-notebook
    state: present
  become: yes

- name: Installation librairies Python Data Science
  pip:
    name:
      - pandas
      - numpy
      - matplotlib
      - scikit-learn
      - jupyterlab
    executable: pip3
  become: yes

- name: Créer un fichier de bienvenue Data Science
  copy:
    content: |
      =====================================
      Cours : Data Science
      Geneva Institute of Technology
      =====================================
      Outils installés : Python3, pandas, numpy, matplotlib, scikit-learn, JupyterLab
      Lancer Jupyter : jupyter lab --ip=0.0.0.0 --port=8888
    dest: /home/ubuntu/cours/README.txt
    owner: ubuntu
  become: yes
